<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  AKHelper
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

class AKHelper extends AKProxy
{
	/**
	 * Gets a list of the actions that can be performed.
	 *
	 * @return	JObject
	 * @since	1.6
	 */
	public static function getActions($option)
	{
		$user	= JFactory::getUser();
		$result	= new JObject;

		$assetName = $option;

		$actions = array(
			'core.admin', 
			'core.manage', 
			'core.create', 
			'core.edit', 
			'core.edit.own', 
			'core.edit.state', 
			'core.delete'
		);

		foreach ($actions as $action) {
			$result->set($action,	$user->authorise($action, $assetName));
		}

		return $result;
	}
	
	
	
	/*
	 * function show
	 * @param $data
	 */
	
	public static function show($data)
	{
		echo '<pre>'.print_r($data, 1).'</pre>' ;
	}
	
	
	/*
	 * function isHome
	 * @param 
	 */
	
	public static function isHome() {
		$juri = JFactory::getURI();
		$current_url = $juri->toString();
		
		if( $juri->base()==$current_url || $juri->base().'index.php' == $current_url ) 
			return true;
		else 
			return false;
	}
}


if(!class_exists('AK')){
	class AK extends AKHelper {}
}