<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  Helpers
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */


// No direct access
defined('_JEXEC') or die;

/**
 * API System Helper
 *
 * @package     Windwalker.Framework
 * @subpackage  Helpers
 */
class AKHelperApi
{
    static protected $sdk_instance = array();
    
    /**
     * init
     */
    public static function initClient( $id, $option = array() )
    {
        $component = $option['component'];
        
        if( substr($component, 0, 4) == 'com_' ) {
            $component = substr($component, 4);
            $compoenent_option = 'com_'.$component;
        }else{
            $compoenent_option = 'com_'.$component;
        }
        
        $option['component']    = $component ;
        $option['option']       = $compoenent_option;
        
        // Include Request SDK
        include_once AKPATH_COMPONENT.'/api/request/item.php' ;
        include_once AKPATH_COMPONENT.'/api/request/list.php' ;
        include_once AKPATH_TABLES.'/api.php' ;
        
        include_once AKPATH_COMPONENT.'/api/sdk.php' ;
        
        // Init SDK
        $params = JComponentHelper::getParams($compoenent_option) ;
        
        $host = $params->get('ApiSystem_Host') ;
        
        if( $host ) {
            $option['host'] = $host;
        }
        
        self::getSDK($id, $option);
    }
    
    /**
     * initServer
     */
    public static function initServer()
    {
        include_once AKPATH_COMPONENT.'/api/response/item.php' ;
        include_once AKPATH_COMPONENT.'/api/response/list.php' ;
        
        include_once AKPATH_COMPONENT.'/api/user/item.php' ;
        //include_once AKPATH_COMPONENT.'/api/user/list.php' ;
    }
    
    /**
     * Get API SDK For AKApi System.
     */
    public static function getSDK( $id = null, $option = array() )
    {
        if(!$id) $id = AKHelper::_('path.getOption');
        
        if(!empty(self::$sdk_instance[$id])) {
            
            return self::$sdk_instance[$id] ;
        
        }else{
            
            $component = $option['component'] ;
            
            self::$sdk_instance[$id] = $service = AKApiSDK::getInstance($option);
            
            return $service;
        }
    }
}