<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  AKHelper
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */


// No direct access
defined('_JEXEC') or die;


class AKHelperIcon {	
	
	/*
	 * function boolean
	 * @param $value
	 */
	
	public static function boolean($value, $task = '', $options = array())
	{
		if( JVERSION >= 3 ) {
			$class = $value ? 'icon-publish' : 'icon-unpublish' ;
			return "<i class=\"{$class}\"></i>" ;
		}else{
			$img = $value ? 'tick.png' : 'publish_x.png' ;
			$img = 'templates/bluestork/images/admin/' . $img ;
			
			$alt = $value ? JArrayHelper::getValue($alt, 'true_alt', 'Yes') : JArrayHelper::getValue($alt, 'false_alt', 'No') ;
			
			return JHtml::_($img, $alt) ;
		}
	}
	
}


