<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  AKHelper
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */


// No direct access
defined('_JEXEC') or die;


class AKHelperJcontent {
	
	public static function getArticleLink( $slug , $catslug = null , $absolute = 0 ) {
		
		include_once JPATH_ROOT.DS.'components'.DS.'com_content'.DS.'helpers'.DS.'route.php' ;
		
		$path = JRoute::_(ContentHelperRoute::getArticleRoute($slug, $catslug));
		$host = str_replace( 'http://'.$_SERVER['HTTP_HOST'] , '' , JURI::root() );
		if( $host != '/' ) $path = str_replace( $host , '' , $path );
		
		if( $absolute ) {
			return AKHelper::_( 'uri.pathAddHost' ,$path);
	    }else{
			return $path ;
		}
		
	}
	
	public static function getCategoryLink( $catid , $absolute = 0) {
		
		include_once JPATH_ROOT.DS.'components'.DS.'com_content'.DS.'helpers'.DS.'route.php' ;
		
		$path = JRoute::_(ContentHelperRoute::getCategoryRoute($catid));
		$host = str_replace( 'http://'.$_SERVER['HTTP_HOST'] , '' , JURI::root() );
		$path = str_replace( $host , '' , $path );
		
		if( $absolute ) {
			return AKHelper::_( 'uri.pathAddHost' ,$path);
	    }else{
			return $path ;
		}
	}
	
}


