<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  AKHelper
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

 
// no direct access
defined('_JEXEC') or die;


class AKHelperPlugin
{
	
	protected static $version ;
	
	protected static $plugins ;
	
	/*
	 * function get
	 * @param 
	 */
	
	public static function get($version)
	{
		if(!empty(self::$version[$version])){
			return true ;
		}
		
		return false ;
	}
	
	/*
	 * function detectVersion
	 * @param 
	 */
	
	public static function attachPlugins()
	{
		jimport('joomla.filesystem.folder');
		$plugins = JFolder::folders(AKHelper::_('path.getAdmin').'/includes/plugins');
		
		if(!$plugins){
			$plugins = array();
		}
		
		foreach( $plugins as $plugin ):
			self::attachPlugin($plugin);
		endforeach;
	}
	
	/*
	 * function attachProPlugin
	 * @param 
	 */
	
	public static function attachPlugin($name)
	{
		$app 	= JFactory::getApplication() ;
		$path 	= AKHelper::_('path.getAdmin') . "/includes/plugins/{$name}/{$name}.php" ;
		$option = JRequest::getVar('option') ;
		$config['params'] = JComponentHelper::getParams($option) ;
		
		if(JFile::exists($path)){
			include_once $path ;
			$dispatcher = JDispatcher::getInstance();
			
			$class_name = 'plg'.ucfirst(str_replace('com_', '', $option)).ucfirst($name) ;
			
			if(class_exists($class_name)){
			
				$plugin = new $class_name($dispatcher, $config);
				$dispatcher->attach($plugin);
				
				self::$plugins[$name] = $plugin;
				self::$version[$name] = true ;
				
				return true ;
			}else{
				return false ;
			}
			
		}else{
			return false ;
		}
		
	}
	
}
