<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_flower
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// No direct access
defined('_JEXEC') or die;
 
/**
 * Script file of HelloWorld component
 *
 * @package     Joomla.Administrator
 * @subpackage  com_flower 
 */
class com_FlowerInstallerScript
{
    /**
     * method to install the component
     *
     * @return void
     */
    function install($parent) 
    {
        
        
    }
 
    /**
     * method to uninstall the component
     *
     * @return void
     */
    function uninstall($parent) 
    {
        
    }
 
    /**
     * method to update the component
     *
     * @return void
     */
    function update($parent) 
    {
        
    }
 
    /**
     * method to run before an install/update/uninstall method
     *
     * @return void
     */
    function preflight($type, $parent) 
    {
        
    }
 
    /**
     * method to run after an install/update/uninstall method
     *
     * @return void
     */
    function postflight($type, $parent) 
    {
        
        $db = JFactory::getDbo();
        
        
        // Get install manifest
        // ========================================================================
        $p_installer    = $parent->getParent() ;
        $installer      = new JInstaller();
        $manifest       = $p_installer->manifest ;
        $path           = $p_installer->getPath('source');
        $result         = array() ;
        
        $css =
<<<CSS
    <style type="text/css">
        #ak-install-img {
            
        }
        
        #ak-install-msg {
            
        }
    </style>
CSS;
        
        echo $css ;
        include_once $path.'/windwalker/admin/installscript.php' ;
    }
    
}