<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_acme
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// No direct access
defined('_JEXEC') or die;

include_once JPATH_LIBRARIES . '/windwalker/Windwalker/init.php';
JForm::addFieldPath(WINDWALKER_SOURCE . '/Form/Fields');
JFormHelper::loadFieldClass('itemlist');

/**
 * Supports an HTML select list of categories
 */
class JFormFieldSunflower_List extends JFormFieldItemlist
{
	/**
	 * The form field type.
	 *
	 * @var string
	 */
	public $type = 'Sunflower_List';

	/**
	 * List name.
	 *
	 * @var string
	 */
	protected $view_list = 'sunflowers';

	/**
	 * Item name.
	 *
	 * @var string
	 */
	protected $view_item = 'sunflower';

	/**
	 * Extension name, eg: com_content.
	 *
	 * @var string
	 */
	protected $extension = 'com_acme';

	/**
	 * Set the published column name in table.
	 *
	 * @var string
	 */
	protected $published_field = 'published';

	/**
	 * Set the ordering column name in table.
	 *
	 * @var string
	 */
	protected $ordering_field = null;
}
