<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_acme
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// No direct access
defined('_JEXEC') or die;

include_once JPATH_LIBRARIES . '/windwalker/Windwalker/init.php';
JForm::addFieldPath(WINDWALKER_SOURCE . '/Form/Fields');
JFormHelper::loadFieldClass('Modal');

/**
 * Supports a modal picker.
 */
class JFormFieldSunflower_Modal extends JFormFieldModal
{
	/**
	 * The form field type.
	 *
	 * @var string
	 * @since    1.6
	 */
	protected $type = 'Sunflower_Modal';

	/**
	 * List name.
	 *
	 * @var string
	 */
	protected $view_list = 'sunflowers';

	/**
	 * Item name.
	 *
	 * @var string
	 */
	protected $view_item = 'sunflower';

	/**
	 * Extension name, eg: com_content.
	 *
	 * @var string
	 */
	protected $extension = 'com_acme';

}
