<?php
namespace Windwalker\DataMapper\Tests;

use Windwalker\Compare\EqCompare;
use Windwalker\DataMapper\OtoDataMapper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-20 at 03:28:45.
 */
class OtoDataMapperTest extends DatabaseTest
{
	/**
	 * @var OtoDataMapper
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		parent::setUp();

		$this->db = static::$dbo;

		$this->object = new OtoDataMapper('a', 'ww_content');

		$this->object->addTable('b', 'ww_content2', new EqCompare('a.id', 'b.content_id'), 'INNER');
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::find
	 * @todo   Implement testFind().
	 */
	public function testFind()
	{
		$result = $this->object->find(array('a.id' => array(6,7,8)), 'a.title', 0, 2);

		$compare = $this->loadToDataset(
<<<SQL
SELECT a.*,
	b.id AS b_id,
	b.content_id AS b_content_id,
	b.mark AS b_mark
FROM ww_content AS a
	INNER JOIN ww_content2 AS b ON a.id = b.content_id
WHERE a.id IN(6,7,8)
ORDER BY a.title
LIMIT 2;
SQL
		);

		$this->assertEquals($compare, $result);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::findAll
	 * @todo   Implement testFindAll().
	 */
	public function testFindAll()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::findOne
	 * @todo   Implement testFindOne().
	 */
	public function testFindOne()
	{
		$result = $this->object->findOne(array('a.id' => array(6,7,8)), 'a.id DESC');

		$compare = $this->loadToData(
			<<<SQL
SELECT a.*,
	b.id AS b_id,
	b.content_id AS b_content_id,
	b.mark AS b_mark
FROM ww_content AS a
	INNER JOIN ww_content2 AS b ON a.id = b.content_id
WHERE a.id IN(6,7,8)
ORDER BY a.id DESC
SQL
		);

		$this->assertEquals($compare, $result);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::create
	 * @todo   Implement testCreate().
	 */
	public function testCreate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::createOne
	 * @todo   Implement testCreateOne().
	 */
	public function testCreateOne()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::update
	 * @todo   Implement testUpdate().
	 */
	public function testUpdate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::updateOne
	 * @todo   Implement testUpdateOne().
	 */
	public function testUpdateOne()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::updateAll
	 * @todo   Implement testUpdateAll().
	 */
	public function testUpdateAll()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::save
	 * @todo   Implement testSave().
	 */
	public function testSave()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::delete
	 * @todo   Implement testDelete().
	 */
	public function testDelete()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::getPrimaryKey
	 * @todo   Implement testGetPrimaryKey().
	 */
	public function testGetPrimaryKey()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::getTable
	 * @todo   Implement testGetTable().
	 */
	public function testGetTable()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::setTable
	 * @todo   Implement testSetTable().
	 */
	public function testSetTable()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::getDataClass
	 * @todo   Implement testGetDataClass().
	 */
	public function testGetDataClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::setDataClass
	 * @todo   Implement testSetDataClass().
	 */
	public function testSetDataClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::getDatasetClass
	 * @todo   Implement testGetDatasetClass().
	 */
	public function testGetDatasetClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Windwalker\DataMapper\AbstractDataMapper::setDatasetClass
	 * @todo   Implement testSetDatasetClass().
	 */
	public function testSetDatasetClass()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
