<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  Form
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

jimport('joomla.html.html');
JFormHelper::loadFieldClass('text');

/**
 * Supports a File finder to pick files.
 *
 * @package     Windwalker.Framework
 * @subpackage  Form
 */
class JFormFieldFinder extends JFormFieldText
{
    /**
     * Method to get the field input markup.
     *
     * @return    string    The field input markup.
     */
    public function getInput()
    {
        // Load the modal behavior script.
        JHtml::_('behavior.modal', 'a.modal');
        
        $this->setScript();

        // Setup variables for display.
        $html    = array();
        $link    = $this->getLink();
        $title   = $this->getTitle();
        

        if (empty($title)) {
            $title = $this->element['select_label']
                        ? (string) JText::_($this->element['select_label'])
                        : JText::_('LIB_WINDWALKER_FORMFIELD_FINDER_SELECT_FILE');
        }
        
        $title = htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
        
        if( JVERSION >=3 ){
            // The current user display field.
            $html[] = '<span class="input-append">';
            $html[] = '<input type="text" class="input-medium" id="'.$this->id.'_name" value="'.$title.'" disabled="disabled" size="35" />
                        <a class="modal btn btn-primary" title="'.JText::_('LIB_WINDWALKER_FORMFIELD_FINDER_BROWSE_FILES').'"  href="'.$link.'&amp;'.JSession::getFormToken().'=1" rel="{handler: \'iframe\', size: {x: 800, y: 450}}">
                            <i class="icon-picture"></i> '.JText::_('LIB_WINDWALKER_FORMFIELD_FINDER_BROWSE_FILES')
                        .'</a>';
            $html[] = '</span>';
        }else{
            AKHelper::_('include.addCSS', 'buttons/delicious-buttons/delicious-buttons.css', 'ww');
            
            // The current user display field.
            $html[] = '<div class="fltlft">';
            $html[] = '  <input type="text" id="'.$this->id.'_name" value="'.$title.'" disabled="disabled" size="35" />';
            $html[] = '</div>';
    
            // The user select button.
            $html[] = '<div class="fltlft">';
            $html[] = '  <div class="">';
            $html[] = '    <a class="modal delicious light blue" title="'.JText::_('LIB_WINDWALKER_FORMFIELD_FINDER_BROWSE_FILES').'"  href="'.$link.'&amp;'.JSession::getFormToken().'=1" rel="{handler: \'iframe\', size: {x: 800, y: 450}}">'.JText::_('LIB_WINDWALKER_FORMFIELD_FINDER_BROWSE_FILES').'</a>';
            $html[] = '  </div>';
            $html[] = '</div>';
        }
        

        // The active article id field.
        if (0 == (int)$this->value) {
            $value = '';
        } else {
            $value = (int)$this->value;
        }

        // class='required' for client side validation
        $class = '';
        if ($this->required) {
            $class = ' class="required modal-value"';
        }

        $html[] = '<input type="hidden" id="'.$this->id.'_link"'.$class.' name="'.$this->name.'" value="'.$value.'" />';

        return implode("\n", $html) ;
    }
    
    /**
     * setScript
     */
    public function setScript()
    {
        // Build the script.
        $script = array();
        $script = <<<SCRIPT
        var AKFinderSelect_{$this->id} = function(selected, elFinder){
            if(selected.length < 1) return ;
            var link    = elFinder.path(selected[0].hash) ;
            var name    = selected[0].name ;
            
            // Clean DS
            link = link.replace(/\\\\/g, '/');
            
            document.id("{$this->id}_link").value = link;
            document.id("{$this->id}_name").value = name;
            SqueezeBox.close();
        } 
SCRIPT;

        // Add the script to the document head.
        JFactory::getDocument()->addScriptDeclaration($script);
    }
    
    /**
     * Get item title.
     */
    public function getTitle()
    {
        $path = $this->value ;
        
        if(!$path) return null ;
        
        $path = JPath::clean($path, '/');
        $path = explode('/', $path);
        
        $file_name = array_pop($path);
        
        return $file_name ;
    }
    
    /**
     * Get item link.
     */
    public function getLink()
    {
        $extension = $this->element['extension'] ? (string) $this->element['extension'] : JRequest::getVar('option') ;
        
        $link = "index.php?option={$extension}&task=elfinderDisplay&tmpl=component&finder_id={$this->id}" ;
        
        return $link ;
    }
}