<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  Form.CCK
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

/**
 * A CCK Engine class. Not available now.
 *
 * @package     Windwalker.Framework
 * @subpackage  Form.CCK 
 */
class AKCCK
{
    
}