<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_flower
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// No direct access
defined('_JEXEC') or die;

/**
 * Main Controller of Flower.
 *
 * @package     Joomla.Administrator
 * @subpackage  com_flower
 */
class FlowerController extends JControllerLegacy
{
	/**
	 * The default view for the display method.
	 *
	 * @var    string
	 * @since  12.2
	 */
	protected $default_view = 'sakura';

	/**
	 * Method to display a view.
	 *
	 * @param  boolean  $cachable   If true, the view output will be cached
	 * @param  mixed    $urlparams  An array of safe url parameters and their variable types, for valid values see {@link JFilterInput::clean()}.
	 *
	 * @return JController   This object to support chaining.
	 *
	 * @since  1.5
	 */
	public function display($cachable = false, $urlparams = false)
	{
		echo 'Display';

		// return parent::display($cachable, $urlparams);
	}
}
