#!/bin/sh
#
# A script to copy component template to windwalker dirs.
# To enable it, copy this file to .git/hooks and add execute permission.
#
# @Date: 2013-12-23
# @Author: Simon Asika <asika32764@gmail.com>

COM="flower"
MOD="flower"
PLG="flower"
GUP="system"

php bin/windwalker.php generator convert com_$COM sakura.sakuras

git add --all
echo "Execute git add" ;

exit 0