<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  class
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;


include_once dirname(__FILE__).'/view.php' ;

class AKViewItem extends AKView
{
	protected 	$items ;
	protected 	$pagination ;
	protected 	$state ;
	
	public		$option  ;
	public		$list_name  ;
	public		$item_name  ;
	
	
	/**
	 * Display the view
	 */
	public function displayWithPanel($tpl = null, $path = null)
	{
		$app = JFactory::getApplication() ;
		
		$this->addToolbar();
		$this->handleFields();
		
		// if is frontend, show toolbar
		if($app->isAdmin())	{
			parent::display($tpl);
		}else{
			parent::displayWithPanel($tpl, $path);
		}
	}

	
	/**
	 * Add the page title and toolbar.
	 *
	 * @since	1.6
	 */
	protected function addToolbar()
	{
		JRequest::setVar('hidemainmenu', true);

		$user		= JFactory::getUser();
		$isNew		= ($this->item->id == 0);

		JToolBarHelper::apply($this->item_name.'.apply');
		JToolBarHelper::save($this->item_name.'.save');
		JToolBarHelper::custom($this->item_name.'.save2new', 'save-new.png', 'save-new_f2.png', 'JTOOLBAR_SAVE_AND_NEW', false);
		JToolBarHelper::custom($this->item_name.'.save2copy', 'save-copy.png', 'save-copy_f2.png', 'JTOOLBAR_SAVE_AS_COPY', false);
		JToolBarHelper::cancel($this->item_name.'.cancel');
	}
	
	
	
	/*
	 * function handleFields
	 * @param 
	 */
	
	public function handleFields()
	{
		$form = $this->form ;
		
		// Nested item, hide parent_id.
		if(!$this->state->get('item.nested')){
			$form->removeField('parent_id', 'basic');
		}
		
	}
	
	
	
	/*
	 * function editFieldsetPanel
	 * @param 
	 */
	
	public function startEditFieldsetPanel($fieldset, $fieldsets)
	{
		$f_tab = $this->get('f_tab') ;
		
		// Get Panel Type
		if(!empty($fieldset->tab)) {
			$panel_type 	= 'tab' ;
			$panel_name 	= $fieldset->tab ;
			$start_function = 'startTabs' ;
			$add_function 	= 'addPanel' ;
		}elseif(!empty($fieldset->slide)) {
			$panel_type 	= 'slide' ;
			$panel_name 	= $fieldset->slide ;
			$start_function = 'startSlider' ;
			$add_function 	= 'addSlide' ;
		}else{
			return true ;
		}
		
		// Set Panel
		if( $panel_name ) {
			if( $fieldset->$panel_type != $f_tab ) {
				echo FlowerHelper::_('panel.' . $start_function , $panel_name . ucfirst($panel_type), array( 'active' => $fieldset->name ) ) ;
				$this->tab_count 	= count( FlowerHelper::_('array.query', $fieldsets, array($panel_type => $panel_name)) ) ;
				$this->tab_num 	= 1 ;
			}
			
			echo FlowerHelper::_('panel.' . $add_function , $fieldset->$panel_type . ucfirst($panel_type), $fieldset->label ? JText::_($fieldset->label) : JText::_('COM_FLOWER_EDIT_FIELDSET_'.$fieldset->name)  , $fieldset->name ) ;
		}
	}
	
	
	
	/*
	 * function editFieldsetPanel
	 * @param 
	 */
	
	public function endEditFieldsetPanel($fieldset)
	{
		// Get Panel Type
		if(!empty($fieldset->tab)) {
			$panel_type 		= 'tab' ;
			$panel_name 		= $fieldset->tab ;
			$endpanel_function 	= 'endPanel' ;
			$end_function 		= 'endTabs' ;
		}elseif(!empty($fieldset->slide)) {
			$panel_type 		= 'slide' ;
			$panel_name 		= $fieldset->slide ;
			$endpanel_function 	= 'endSlide' ;
			$end_function 		= 'endSlider' ;
		}else{
			return true ;
		}
		
		
		// Tabs & Slides end
		if(!empty( $fieldset->$panel_type) ) {
			echo FlowerHelper::_('panel.' . $endpanel_function , $panel_name . ucfirst($panel_type), $fieldset->name ) ;
		}
		
		if( $this->tab_num == $this->tab_count ) {
			echo FlowerHelper::_('panel.' . $end_function ) ;
		}
		
		$this->f_tab = !empty($panel_name) ? $fieldset->$panel_type : null;
		$this->tab_num++ ;
	}
}